trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn
    yarn build
    firebase deploy --token $FIREBASE_TOKEN
  displayName: 'npm install and build'
