/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125CvRouteImport } from './routes/{-$locale}/cv'
import { Route as Char123LocaleChar125DocsIndexRouteImport } from './routes/{-$locale}/docs/index'
import { Route as Char123LocaleChar125BlogIndexRouteImport } from './routes/{-$locale}/blog/index'
import { Route as Char123LocaleChar125DocsPolitiqueConfidentialiteRouteImport } from './routes/{-$locale}/docs/politique-confidentialite'
import { Route as Char123LocaleChar125DocsMentionsLegalesRouteImport } from './routes/{-$locale}/docs/mentions-legales'
import { Route as Char123LocaleChar125DocsSlugRouteImport } from './routes/{-$locale}/docs/$slug'
import { Route as Char123LocaleChar125BlogSlugRouteImport } from './routes/{-$locale}/blog/$slug'
import { Route as ContentContentLocaleHomeDottxtRouteImport } from './routes/content/$contentLocale/home[.]txt'
import { Route as ContentContentLocaleHomeDotmdRouteImport } from './routes/content/$contentLocale/home[.]md'
import { Route as ContentContentLocaleDocsSplatRouteImport } from './routes/content/$contentLocale/docs/$'
import { Route as ContentContentLocaleBlogSplatRouteImport } from './routes/content/$contentLocale/blog/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125CvRoute = Char123LocaleChar125CvRouteImport.update({
  id: '/{-$locale}/cv',
  path: '/{-$locale}/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125DocsIndexRoute =
  Char123LocaleChar125DocsIndexRouteImport.update({
    id: '/{-$locale}/docs/',
    path: '/{-$locale}/docs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125BlogIndexRoute =
  Char123LocaleChar125BlogIndexRouteImport.update({
    id: '/{-$locale}/blog/',
    path: '/{-$locale}/blog/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DocsPolitiqueConfidentialiteRoute =
  Char123LocaleChar125DocsPolitiqueConfidentialiteRouteImport.update({
    id: '/{-$locale}/docs/politique-confidentialite',
    path: '/{-$locale}/docs/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DocsMentionsLegalesRoute =
  Char123LocaleChar125DocsMentionsLegalesRouteImport.update({
    id: '/{-$locale}/docs/mentions-legales',
    path: '/{-$locale}/docs/mentions-legales',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DocsSlugRoute =
  Char123LocaleChar125DocsSlugRouteImport.update({
    id: '/{-$locale}/docs/$slug',
    path: '/{-$locale}/docs/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125BlogSlugRoute =
  Char123LocaleChar125BlogSlugRouteImport.update({
    id: '/{-$locale}/blog/$slug',
    path: '/{-$locale}/blog/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentContentLocaleHomeDottxtRoute =
  ContentContentLocaleHomeDottxtRouteImport.update({
    id: '/content/$contentLocale/home.txt',
    path: '/content/$contentLocale/home.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentContentLocaleHomeDotmdRoute =
  ContentContentLocaleHomeDotmdRouteImport.update({
    id: '/content/$contentLocale/home.md',
    path: '/content/$contentLocale/home.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentContentLocaleDocsSplatRoute =
  ContentContentLocaleDocsSplatRouteImport.update({
    id: '/content/$contentLocale/docs/$',
    path: '/content/$contentLocale/docs/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentContentLocaleBlogSplatRoute =
  ContentContentLocaleBlogSplatRouteImport.update({
    id: '/content/$contentLocale/blog/$',
    path: '/content/$contentLocale/blog/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/cv': typeof Char123LocaleChar125CvRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/content/$contentLocale/home.md': typeof ContentContentLocaleHomeDotmdRoute
  '/content/$contentLocale/home.txt': typeof ContentContentLocaleHomeDottxtRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/docs/$slug': typeof Char123LocaleChar125DocsSlugRoute
  '/{-$locale}/docs/mentions-legales': typeof Char123LocaleChar125DocsMentionsLegalesRoute
  '/{-$locale}/docs/politique-confidentialite': typeof Char123LocaleChar125DocsPolitiqueConfidentialiteRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsIndexRoute
  '/content/$contentLocale/blog/$': typeof ContentContentLocaleBlogSplatRoute
  '/content/$contentLocale/docs/$': typeof ContentContentLocaleDocsSplatRoute
}
export interface FileRoutesByTo {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/cv': typeof Char123LocaleChar125CvRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/content/$contentLocale/home.md': typeof ContentContentLocaleHomeDotmdRoute
  '/content/$contentLocale/home.txt': typeof ContentContentLocaleHomeDottxtRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/docs/$slug': typeof Char123LocaleChar125DocsSlugRoute
  '/{-$locale}/docs/mentions-legales': typeof Char123LocaleChar125DocsMentionsLegalesRoute
  '/{-$locale}/docs/politique-confidentialite': typeof Char123LocaleChar125DocsPolitiqueConfidentialiteRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsIndexRoute
  '/content/$contentLocale/blog/$': typeof ContentContentLocaleBlogSplatRoute
  '/content/$contentLocale/docs/$': typeof ContentContentLocaleDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/cv': typeof Char123LocaleChar125CvRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/content/$contentLocale/home.md': typeof ContentContentLocaleHomeDotmdRoute
  '/content/$contentLocale/home.txt': typeof ContentContentLocaleHomeDottxtRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/docs/$slug': typeof Char123LocaleChar125DocsSlugRoute
  '/{-$locale}/docs/mentions-legales': typeof Char123LocaleChar125DocsMentionsLegalesRoute
  '/{-$locale}/docs/politique-confidentialite': typeof Char123LocaleChar125DocsPolitiqueConfidentialiteRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/docs/': typeof Char123LocaleChar125DocsIndexRoute
  '/content/$contentLocale/blog/$': typeof ContentContentLocaleBlogSplatRoute
  '/content/$contentLocale/docs/$': typeof ContentContentLocaleDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/{-$locale}/cv'
    | '/{-$locale}'
    | '/content/$contentLocale/home.md'
    | '/content/$contentLocale/home.txt'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/docs/$slug'
    | '/{-$locale}/docs/mentions-legales'
    | '/{-$locale}/docs/politique-confidentialite'
    | '/{-$locale}/blog'
    | '/{-$locale}/docs'
    | '/content/$contentLocale/blog/$'
    | '/content/$contentLocale/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/{-$locale}/cv'
    | '/{-$locale}'
    | '/content/$contentLocale/home.md'
    | '/content/$contentLocale/home.txt'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/docs/$slug'
    | '/{-$locale}/docs/mentions-legales'
    | '/{-$locale}/docs/politique-confidentialite'
    | '/{-$locale}/blog'
    | '/{-$locale}/docs'
    | '/content/$contentLocale/blog/$'
    | '/content/$contentLocale/docs/$'
  id:
    | '__root__'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/{-$locale}/cv'
    | '/{-$locale}/'
    | '/content/$contentLocale/home.md'
    | '/content/$contentLocale/home.txt'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/docs/$slug'
    | '/{-$locale}/docs/mentions-legales'
    | '/{-$locale}/docs/politique-confidentialite'
    | '/{-$locale}/blog/'
    | '/{-$locale}/docs/'
    | '/content/$contentLocale/blog/$'
    | '/content/$contentLocale/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LocaleChar125CvRoute: typeof Char123LocaleChar125CvRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  ContentContentLocaleHomeDotmdRoute: typeof ContentContentLocaleHomeDotmdRoute
  ContentContentLocaleHomeDottxtRoute: typeof ContentContentLocaleHomeDottxtRoute
  Char123LocaleChar125BlogSlugRoute: typeof Char123LocaleChar125BlogSlugRoute
  Char123LocaleChar125DocsSlugRoute: typeof Char123LocaleChar125DocsSlugRoute
  Char123LocaleChar125DocsMentionsLegalesRoute: typeof Char123LocaleChar125DocsMentionsLegalesRoute
  Char123LocaleChar125DocsPolitiqueConfidentialiteRoute: typeof Char123LocaleChar125DocsPolitiqueConfidentialiteRoute
  Char123LocaleChar125BlogIndexRoute: typeof Char123LocaleChar125BlogIndexRoute
  Char123LocaleChar125DocsIndexRoute: typeof Char123LocaleChar125DocsIndexRoute
  ContentContentLocaleBlogSplatRoute: typeof ContentContentLocaleBlogSplatRoute
  ContentContentLocaleDocsSplatRoute: typeof ContentContentLocaleDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/cv': {
      id: '/{-$locale}/cv'
      path: '/{-$locale}/cv'
      fullPath: '/{-$locale}/cv'
      preLoaderRoute: typeof Char123LocaleChar125CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/docs/': {
      id: '/{-$locale}/docs/'
      path: '/{-$locale}/docs'
      fullPath: '/{-$locale}/docs'
      preLoaderRoute: typeof Char123LocaleChar125DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/blog/': {
      id: '/{-$locale}/blog/'
      path: '/{-$locale}/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof Char123LocaleChar125BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/docs/politique-confidentialite': {
      id: '/{-$locale}/docs/politique-confidentialite'
      path: '/{-$locale}/docs/politique-confidentialite'
      fullPath: '/{-$locale}/docs/politique-confidentialite'
      preLoaderRoute: typeof Char123LocaleChar125DocsPolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/docs/mentions-legales': {
      id: '/{-$locale}/docs/mentions-legales'
      path: '/{-$locale}/docs/mentions-legales'
      fullPath: '/{-$locale}/docs/mentions-legales'
      preLoaderRoute: typeof Char123LocaleChar125DocsMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/docs/$slug': {
      id: '/{-$locale}/docs/$slug'
      path: '/{-$locale}/docs/$slug'
      fullPath: '/{-$locale}/docs/$slug'
      preLoaderRoute: typeof Char123LocaleChar125DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/blog/$slug': {
      id: '/{-$locale}/blog/$slug'
      path: '/{-$locale}/blog/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof Char123LocaleChar125BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentLocale/home.txt': {
      id: '/content/$contentLocale/home.txt'
      path: '/content/$contentLocale/home.txt'
      fullPath: '/content/$contentLocale/home.txt'
      preLoaderRoute: typeof ContentContentLocaleHomeDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentLocale/home.md': {
      id: '/content/$contentLocale/home.md'
      path: '/content/$contentLocale/home.md'
      fullPath: '/content/$contentLocale/home.md'
      preLoaderRoute: typeof ContentContentLocaleHomeDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentLocale/docs/$': {
      id: '/content/$contentLocale/docs/$'
      path: '/content/$contentLocale/docs/$'
      fullPath: '/content/$contentLocale/docs/$'
      preLoaderRoute: typeof ContentContentLocaleDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentLocale/blog/$': {
      id: '/content/$contentLocale/blog/$'
      path: '/content/$contentLocale/blog/$'
      fullPath: '/content/$contentLocale/blog/$'
      preLoaderRoute: typeof ContentContentLocaleBlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LocaleChar125CvRoute: Char123LocaleChar125CvRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  ContentContentLocaleHomeDotmdRoute: ContentContentLocaleHomeDotmdRoute,
  ContentContentLocaleHomeDottxtRoute: ContentContentLocaleHomeDottxtRoute,
  Char123LocaleChar125BlogSlugRoute: Char123LocaleChar125BlogSlugRoute,
  Char123LocaleChar125DocsSlugRoute: Char123LocaleChar125DocsSlugRoute,
  Char123LocaleChar125DocsMentionsLegalesRoute:
    Char123LocaleChar125DocsMentionsLegalesRoute,
  Char123LocaleChar125DocsPolitiqueConfidentialiteRoute:
    Char123LocaleChar125DocsPolitiqueConfidentialiteRoute,
  Char123LocaleChar125BlogIndexRoute: Char123LocaleChar125BlogIndexRoute,
  Char123LocaleChar125DocsIndexRoute: Char123LocaleChar125DocsIndexRoute,
  ContentContentLocaleBlogSplatRoute: ContentContentLocaleBlogSplatRoute,
  ContentContentLocaleDocsSplatRoute: ContentContentLocaleDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
